### ISSUE TITLE
Make NO_PROXY lists customizable

### ISSUE THREAD

**Issue by Zekfad** [Rob--W/proxy-from-env#11]
# Feature request

Expose `NO_PROXY` lists outside as options or editable prototype property.

# Why?

This will allow to use custom no-proxy lists from outside. E.g. like `node-gyp` use it's own no-proxy implementation.

# References

https://github.com/Rob--W/proxy-from-env/blob/96d01f8fcfdccfb776735751132930bbf79c4a3a/index.js#L63

**Comment by Rob--W** [comment]
Closing because of https://github.com/Rob--W/proxy-from-env/pull/12#issuecomment-698283916
