### ISSUE TITLE
License

### ISSUE THREAD

**Issue by parvathi** [Rob--W/proxy-from-env#6]
Hi,

We are trying to use Puppeteer library for PDF generation which has a dependency on proxy-from-env. Our company requires License information for software approval. I see that package.json mentions MIT license. But there is no explicit license file or details as its usually mentioned in node libraries. Wondering if its possible to upload a license file. 

thanks
Parvathi

**Comment by Rob--W** [comment]
I repeat here - this package is published under the MIT license.

**Comment by johnjbarton** [comment]
@Rob--W Just to try to explain: the  "license": "MIT" in the package.json is similar to a forward-declaration as far as lawyers are concerned.  It declares that the MIT license should be expected. The LICENSE file is the value that satisfies the declaration. 

The procedure of using the LICENSE file as the standard location for the open source license has been worked out over a long period of time. Software tools have been built to verify this file. It's like a standard protocol for communicating with lawyers.  

I hope this explains PR #7.
