### ISSUE TITLE
Respect NPM configuration

### ISSUE THREAD

**Issue by aslushnikov** [Rob--W/proxy-from-env#8]
NPM can define it's own [proxy settings](https://docs.npmjs.com/misc/config#proxy), and these are set as `process.env.npm_config_https_proxy`, `process.env.npm_config_http_proxy`, and `process.env.npm_config_no_proxy`.

proxy-form-env does not respect these, and the only way to use these with `proxy-form-env` is to spoil the global scope:

https://github.com/puppeteer/puppeteer/blob/0b1a9ceee2f05f534f0d50079ece172d627a93c7/install.js#L54-L65

It'd be nice to support these out of the box, or at least have an option to plug them in.

**Comment by Rob--W** [comment]
@aslushnikov FYI I have published a new version last week, which includes your patch.

**Comment by aslushnikov** [comment]
@Rob--W thanks! I already picked it up in Playwright :) https://github.com/microsoft/playwright/commit/14a7d1c656b41a2ecad23d3e29c4bade2590aac7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
